services:
  sta:
    restart: always
    image: ichiharanaruki/fiberdev:latest
    container_name: 'sta'
    working_dir: '/home/'
    tty: true
    volumes:
      - ./:/home/usr/mounted
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /mnt/wslg:/mnt/wslg
    shm_size: 4gb
    environment:
      - DISPLAY=$DISPLAY
      - WAYLAND_DISPLAY=$WAYLAND_DISPLAY
      - XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR
      - PULSE_SERVER=$PULSE_SERVER
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all

    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]